# Generated by Django 6.1.1 on 2026-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                # Django crea 'id' automaticamente. 
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio_gramo', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
    ]
