# Generated by Django 6.1.1 on 2026-09-30 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai3d_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichero', models.FileField(upload_to='impresiones/')),
                ('volumen_cm3', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('peso_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad', models.PositiveBigIntegerField(default=1)),
                ('notas', models.TextField(blank=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kai3d_app.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
