# Generated by Django 6.1.1 on 2026-09-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai3d_app', '0002_impresion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresion',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
