# Generated by Django 6.1.1 on 2026-10-01 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kai3d_app', '0004_alter_impresion_usuario_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
