# Generated by Django 6.1.1 on 2026-10-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai3d_app', '0005_delete_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En revision', 'En revision'), ('Presupuesto', 'Presupuesto'), ('Listo para recoger', 'Listo para recoger'), ('Recogido', 'Recogido'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=30),
        ),
    ]
