# Generated by Django 6.1.1 on 2026-10-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai3d_app', '0006_alter_impresion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='densidad',
            field=models.DecimalField(decimal_places=3, default=1.24, max_digits=6),
        ),
    ]
