# Generated by Django 6.1.1 on 2026-10-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kai3d_app', '0007_material_densidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='coste_material',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
